### ISSUE TITLE
"CarveraController" is damaged and can't be opened on MacOS 13.6.3

### ISSUE THREAD

**Issue by eric2777** [MakeraInc/CarveraController#20]
After fresh install of CarveraController v0.9.6 binary downloaded from this repository, macOS generated the following error
![image](https://github.com/MakeraInc/CarveraController/assets/76942169/18464769-f634-4a6e-b9e0-26907ad066fa)

**Comment by MakeraInc** [comment]
Please see the solution at:
[https://github.com/MakeraInc/CarveraController?tab=readme-ov-file#macosx-installation](https://github.com/MakeraInc/CarveraController?tab=readme-ov-file#macosx-installation)

**Comment by eric2777** [comment]
Thanks for the information. After running attr, I don't get the previous error but the app doesn't start and crash silently.
I ran the other terminal command as explained and I get the following error:

![image](https://github.com/MakeraInc/CarveraController/assets/76942169/c51e701f-3c8b-4477-8792-22b68009e654)

**Comment by eric2777** [comment]
My bad, I just downloaded the latest build that was released 3 days ago, and now I can launch the app. So this issue can be closed now. thanks

**Comment by eric2777** [comment]
fixed in latest version
